# Generated by Django 4.0.3 on 2022-03-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.PositiveIntegerField()),
                ('information', models.CharField(max_length=4256)),
            ],
        ),
        migrations.AlterField(
            model_name='performance',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='songs_app.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='composer', to='songs_app.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='writer', to='songs_app.artist'),
        ),
        migrations.DeleteModel(
            name='Composer',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
