# Generated by Django 4.0.3 on 2022-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0002_artist_alter_performance_singer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(through='songs_app.Performance', to='songs_app.artist'),
        ),
    ]
