# Generated by Django 4.0.3 on 2022-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0012_performance_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
