# Generated by Django 4.0.3 on 2022-03-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0008_rename_singer_song_performance_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Performance_by',
            new_name='performed_by',
        ),
    ]
