# Generated by Django 4.0.3 on 2022-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0011_remove_performance_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
