# Generated by Django 4.0.3 on 2022-04-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0014_remove_review_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='performed_by',
        ),
        migrations.AlterField(
            model_name='review',
            name='Performance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs_app.performance'),
        ),
    ]
