# Generated by Django 4.0.3 on 2022-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0016_alter_performance_singer_alter_performance_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
