# Generated by Django 4.0.3 on 2022-04-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0017_artist_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='photo',
        ),
    ]
