# Generated by Django 4.0.3 on 2022-04-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0018_remove_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(default=1, upload_to='songs/artist'),
            preserve_default=False,
        ),
    ]
