# Generated by Django 4.0.3 on 2022-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0019_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
