# Generated by Django 4.0.3 on 2022-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0024_song_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.URLField(blank=True, max_length=4256, null=True),
        ),
    ]
